name: Build and Release Kodi Addon

on:
  push:
    branches: [ main, master ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch full history for git operations

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install kodi-addon-builder
      run: |
        # Install from git (replace with your repo URL)
        pip install git+https://github.com/yourusername/kodi-addon-builder.git

    - name: Build zip artifact (on push/PR)
      if: github.event_name != 'push' || !startsWith(github.ref, 'refs/tags/')
      run: |
        kodi-addon-builder zip --output addon.zip

    - name: Upload artifact (on push/PR)
      if: github.event_name != 'push' || !startsWith(github.ref, 'refs/tags/')
      uses: actions/upload-artifact@v4
      with:
        name: kodi-addon
        path: addon.zip
        if-no-files-found: error

    - name: Build and release zip (on tag)
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        kodi-addon-builder zip --output ${{ github.event.repository.name }}-${{ github.ref_name }}.zip

    - name: Create GitHub Release (on tag)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        files: ${{ github.event.repository.name }}-${{ github.ref_name }}.zip
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}